### ISSUE TITLE
template does not start a build / build an image! 

### ISSUE THREAD

**Issue by sferich888** [sclorg/nginx-ex#2]
```
oc start-build nginxhosting
The ImageStreamTag "nginx:1.12" is invalid: from: Error resolving ImageStreamTag nginx:1.12 in namespace openshift: imagestreams.image.openshift.io "nginx" not found
```
This seems to be caused by https://github.com/sclorg/nginx-ex/blob/staging/openshift/templates/nginx.json#L96 

- Note: This may not be a bug with the template but a bug with my clusters registry search parameters, in that it can't find the correct image to pull.

**Comment by sferich888** [comment]
- Note: this is caused by running: `oc newapp --tempate nginx-example` using he defined template. 
`oc new-app centos/nginx-112-centos7~https://github.com/sclorg/nginx-ex`successfully deploys a container.

**Comment by sferich888** [comment]
Another key problem is that https://access.redhat.com/containers/?build_categories_list=Builder%20Image#/search/rhscl does not list an RHSCL image for RHEL (but I assume one is in the pipline given https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhscl-beta/nginx-112-rhel7

**Comment by pvalena** [comment]
Yes, only beta is available, that's why this repo is still in staging.
**This is really not production material and should not be used as of now, apart from testing purposes.**

**Comment by pvalena** [comment]
We do not intent to make this compatible with beta.
